### ISSUE TITLE
[levante] Strange problem in IO

### ISSUE THREAD

**Issue by PengyangSong** [FESOM/fesom2#413] opened 2023-01-19 10:48 UTC
Dear developers,
I am on the refactoring branch, and on levante.
https://github.com/FESOM/fesom2/blob/refactoring/src/CMakeLists.txt#L37
levante cannot run FESOM2 with this OFF, should be ON.
@hegish @patrickscholz

**Comment by PengyangSong** [comment] 2023-01-19 10:49
slurm-err.out:
221: terminate called after throwing an instance of 'std::system_error'
221:   what():  Resource temporarily unavailable
......

**Comment by hegish** [comment] 2023-01-19 10:54
What happens with the default setting? Can you provide a full log?

**Comment by PengyangSong** [comment] 2023-01-19 11:15
Hi @hegish 
/home/a/a270146/work/fesom2_test/work/slurm-err.out.3450039
in case you cannot access to project ab0246, I copy the folder to below.
/home/a/a270146/for_hegish/fesom2_test/work/slurm-err.out.3450039

**Comment by hegish** [comment] 2023-01-19 14:28
Thenk you for the file. It looks similar to a problem @patrickscholz has observed. Did it work for you before Tuesday this week? Or did it never run?

**Comment by PengyangSong** [comment] 2023-01-19 14:32
last week I use refactoring_bugfix_cavity, and this week I change to refactoring. I found this line because I compared both branches. I cannot tell if this works before Tuesday of this week.

**Comment by hegish** [comment] 2023-01-19 14:37
OK, I will contact DKRZ and see if I can reproduce the problem.

**Comment by hegish** [comment] 2023-01-19 14:48
We do not want to disable it everywhere! Should I change the CMakeLists.txt to have it off only on levante?

**Comment by patrickscholz** [comment] 2023-01-19 14:52
Maybe for the moment until we have a better solution it would make sense to DISABLE_MULTITHREADING for levante i guess more FESOM2 levante user will run into that issue.

**Comment by patrickscholz** [comment] 2023-01-19 14:59
yes,  Until we have a better solution.

**Comment by hegish** [comment] 2023-01-19 15:30
I have created a PR https://github.com/FESOM/fesom2/pull/414

**Comment by n-beech** [comment] 2023-01-20 08:46
I have also been experiencing this issue. I just tried running fesom again with your bug fix but I am still getting the error.

**Comment by patrickscholz** [comment] 2023-01-20 08:57
@n-beech you might need to completely delete the build/ folder and recompile...

**Comment by hegish** [comment] 2023-01-20 09:19
> I have also been experiencing this issue. I just tried running fesom again with your bug fix but I am still getting the error.

Could you show us the full error log?

**Comment by n-beech** [comment] 2023-01-20 10:24
Thanks, I think removing the build folder before reconfiguring worked.
The error log is here if you still want it.
/home/a/a270166/error_log/

**Comment by hegish** [comment] 2023-01-25 14:36
I discussed this issue with DKRZ. Turns out they have inadvertently limited the number of threads on the compute nodes! This could very likely be the cause for the "Resource temporarily unavailable" errors.
The issue should be fixed now, could you try to re-run FESOM with `DISABLE_MULTITHREADING=OFF` and report back here if it is working again?

**Comment by PengyangSong** [comment] 2023-01-27 08:24
@hegish Solved!

I did the test from 'git clone .....' and it works now with `DISABLE_MULTITHREADING=OFF`.
```
git diff src/CMakeLists.txt
```
```
 if(${FESOM_PLATFORM_STRATEGY} STREQUAL  levante.dkrz.de )
    message(STATUS "multithreading disabled for Levante") # multithreading suddenly produces an error, disable it until a fix is found. issue #413
-   option(DISABLE_MULTITHREADING "disable asynchronous operations" ON)
+   option(DISABLE_MULTITHREADING "disable asynchronous operations" OFF)
 else()
    option(DISABLE_MULTITHREADING "disable asynchronous operations" OFF)
 endif()

```

**Comment by hegish** [comment] 2023-01-27 08:47
Great!

**Comment by PengyangSong** [comment] 2023-02-22 07:45
> Can we fix it in the `refactoring` now?

Hi @koldunovn , at least the Levante problem is fixed. You can run with `DISABLE_MULTITHREADING OFF`.
But as to Albedo I have no idea.
https://github.com/FESOM/fesom2/blob/refactoring/src/CMakeLists.txt#L41

**Comment by hegish** [comment] 2023-02-23 12:01
The issue should not exist anymore, there was a configuration error on the levante compute nodes regarding the creation of threads. According to DKRZ it has been fixed, so the workaround is no longer needed.

**Closed** 2024-08-27 07:44 UTC
